### ISSUE TITLE
input_tar.gz GDT_TS labels

### ISSUE THREAD

**Issue by jasoank** [Bhattacharya-Lab/QDeep#3]
I'm trying to replicate QDeep using the dataset provided in the input_tar.gz file. However, in the CASP 13 stage 2 dataset that included in the input_tar.gz file, only predicted labels are available while the actual labels are needed as well. I'm sorry I might missing something, but when I parsed the official GDT_TS labels directly from the official CASP13 website, there are prediction models that didn't have official GDT_TS score but are predicted by QDeep.
For example:
Pool name: T0955
Group and TS name:  BAKER_ROSETTASERVER_TS1 - TS5 

Thank you

**Comment by Bhattacharya-Lab** [comment]
The official GDT_TS score for a predicted 3D model can be calculated using the LGA program (https://pubmed.ncbi.nlm.nih.gov/12824330/) after downloading the predicted 3D model and the corresponding experimental structure from the CASP website.
